### ISSUE TITLE
Unable to make it work

### ISSUE THREAD

**Issue by mauriziod** [Benoss/PreTty-Query-Digest#1]
Hi, is it possible to get some recommendations on how to run this tool. Looks like it could be very helpful for what I am trying to achieve. 

I am trying to execute the parser like this using python2.7 and python3.6.4 and pt-query-digest 3.0.9:

```
python /tmp/PreTty-Query-Digest/launch.py --report_path /tmp/ --no_server slowquery.log
```
```
Starting pt-query-digest for slowquery.log
Traceback (most recent call last):
  File "/tmp/PreTty-Query-Digest/launch.py", line 36, in <module>
    parsed_result = run_pt_query.run(args.file_name)
  File "/private/tmp/PreTty-Query-Digest/src/run_pt_query.py", line 33, in run
    decoded_response = json.loads(json_response)
  File "/Users/xuserx/.pyenv/versions/3.6.4/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/Users/xuserx/.pyenv/versions/3.6.4/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/Users/xuserx/.pyenv/versions/3.6.4/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Any chance I can pass directly the pt-query-digest report in JSON format to only visualise?

**Comment by Benoss** [comment]
Sorry I haven't updated this repo in 4 years it is possible that since then the format changed
